language: generic
sudo: required
services:
  - docker 

before_install:
  - docker build -t busmani84/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true busmani84/react-test npm test 

after_sucess:
  - docker build -t busmani84/multi-client ./client
  - docker build -t busmani84/multi-nginx ./nginx
  - docker build -t busmani84/multi-server ./server
  - docker build -t busmani84/multi-worker ./worker

  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take those images and push them to docker hub
  - docker push busmani84/multi-client
  - docker push busmani84/multi-nginx
  - docker push busmani84/multi-server
  - docker push busmani84/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  regin: us-east-1
  app: multi_docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-077775822785
  bucket_path: docker-multi

  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

 